/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package journey.fx;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
